.TH "ecatools" "1" "14\&.10\&.2001" "" "Multimedia software" 
.PP 
.SH "NAME" 
ecatools \- audio processing utils based on ecasound
.PP 
.SH "SYNOPSIS" 
\fBecaconvert\fP \&.extension file1 [ file2,\&.\&.\&.,fileN ]
.PP 
\fBecafixdc\fP file1 [ file2,\&.\&.\&.,fileN ]
.PP 
\fBecalength\fP file1 [ file2,\&.\&.\&.,fileN ]
.PP 
\fBecanormalize\fP file1 [ file2,\&.\&.\&.,fileN ]
.PP 
\fBecaplay\fP [-dhk] file1 [ file2,\&.\&.\&.,fileN ]
.PP 
\fBecasignalview\fP [ options ] [ input ] [ output ]
.PP 
.SH "DESCRIPTION" 
.PP 
Ecatools are simple command line utils that do various audio
processing tasks\&. Most of them support batch processing\&. They all
use the ecasound engine (libecasound)\&.
.PP 
\fBECACONVERT\fP
.PP 
A tool for converting a set of files to a common target format\&.
This target format is given as the first command line
argument, and its syntax is \fI\&.ext\fP\&.
.PP 
\fBECAFIXDC\fP
.PP 
A simple command-line tool for fixing DC-offset\&.
.PP 
\fBECALENGTH\fP
.PP 
See ecalength(1) man page\&.
.PP 
\fBECANORMALIZE\fP
.PP 
A simple command-line tool for normalizing sample volume\&. 
Finds out how much input file can be amplified without clipping
and, if necessary, does the amplification\&.
.PP 
\fBECAPLAY\fP
.PP 
A simple command-line tool that plays input files using the
default output specified in \fI~/\&.ecasoundrc\fP\&. Note! You  can abort 
ecaplay at any time by pressing Ctrl-C\&. If you are playing multiple 
files, this will stop the current file and begin playing the next one\&.  
If you want to abort playing immediately instead of skipping to the 
next file, press Ctrl-C twice in short succession (around one
second)\&.
.PP 
.IP "-d:debuglevel" 
Set libecasound debug level\&. See ecasound(1)\&.
.IP 
.IP "-h" 
Print usage information and exit\&.
.IP 
.IP "-k:number" 
Skip \'number\' of files\&.
.IP 
.PP 
\fBECASIGNALVIEW\fP
.PP 
Ecasignalview is meant for monitoring signal amplitude and peak 
statistics\&. It accepts the following options:
.PP 
.IP "input" 
The first option not starting with a \'-\' is interpreted 
as input string\&. This can be a device or a filename\&. All formats
supported by libecasound are accepted\&. Defaults to \'/dev/dsp\'\&.
.IP 
.IP "output" 
Similarly to input, second option not starting with a \'-\'
is interpreted as output\&. Defaults to \'null\'\&.
.IP 
.IP "-b:buffersize" 
Buffersize in sample frames\&. Defaults to 128\&.
.IP 
.IP "-c" 
Enable cumulative mode\&. Counters are not reseted after refresh\&.
.IP 
.IP "-d" 
Enable debug mode\&.
.IP 
.IP "-f:format_string" 
Specify default audio format\&. See ecasound(1) for details\&.
.IP 
.IP "-r:rate_msec" 
Specify screen refresh rate in milliseconds\&.
.PP 
.SH "FILES" 
.PP 
\fI~/\&.ecasoundrc\fP
The default ecasound resource file\&. If the file doesn\'t exist, it 
is created with some default values\&. See ecasoundrc(5)\&.
.PP 
.SH "SEE ALSO" 
.PP 
ecasound (1), ecalength(1), "HTML docs in the Documentation subdirectory"
.PP 
.SH "AUTHOR" 
.PP 
Kai Vehmanen, <kaiv@wakkanet\&.fi>
.PP 
