.TH "ecatools" "1" "21\&.05\&.2000" "" "Multimedia software" 
.PP 
.SH "NAME" 
ecatools \- audio processing utils based on ecasound
.PP 
.SH "SYNOPSIS" 
\fBecafixdc\fP file1 [ file2,\&.\&.\&.,fileN ]
.PP 
\fBecanormalize\fP file1 [ file2,\&.\&.\&.,fileN ]
.PP 
\fBecaplay\fP file1 [ file2,\&.\&.\&.,fileN ]
.PP 
.SH "DESCRIPTION" 
.PP 
Ecatools are simple command line utils that do various audio
processing tasks\&. Most of them support batch processing\&. They all
use the ecasound engine (libecasound)\&.
.PP 
\fBECAFIXDC\fP
.PP 
A simple command-line tool for fixing DC-offset\&.
.PP 
\fBECANORMALIZE\fP
.PP 
A simple command-line tool for normalizing sample volume\&. 
Finds out how much input file can be amplified without clipping
and, if necessary, does the amplification\&.
.PP 
\fBECAPLAY\fP
.PP 
A simple command-line tool that plays input files using the
default output specified in \fI~/\&.ecasoundrc\fP\&.
.PP 
.SH "FILES" 
.PP 
\fI~/\&.ecasoundrc\fP
The default ecasound resource file\&. If the file doesn\'t exist, it 
is created with some default values\&. See ecasoundrc(5)\&.
.PP 
.SH "SEE ALSO" 
.PP 
ecasound (1), "HTML docs in the Documentation subdirectory",
qtecasound (1)
.PP 
.SH "AUTHOR" 
.PP 
Kai Vehmanen, <kaiv@wakkanet\&.fi>
.PP 
